// Shared English guide chrome. Translations live in guide-locales/<locale>.json.
module.exports = {
  indexTitle: 'Browser tab guides',
  indexDescription: 'Practical TabTools guides for closing tabs from one website, removing duplicate tabs and sorting tabs by site in Chrome, Firefox and Edge.',
  indexEyebrow: 'TabTools guides',
  indexHeading: 'A clearer tab bar.',
  indexHeadingAccent: 'One task at a time.',
  indexLede: 'Close a website’s tabs, clear repeated pages or bring related tabs together. Pick a guide and follow the steps in your browser.',
  indexPlatforms: 'For Chrome, Firefox and Edge on desktop',
  startEyebrow: 'New to TabTools?',
  startHeading: 'Three ways to tidy up.',
  startBody: 'Closing by site removes a website’s pages. Duplicate cleanup removes repeated URLs. Sorting keeps your tabs open and changes their order. Each guide explains what happens, with examples and browser alternatives.',
  explore: 'Explore TabTools',
  browseGuides: 'Browse guides',
  readGuide: 'Read guide',
  readTime: '{minutes} min read',
  getTabTools: 'Get TabTools',
  installEyebrow: 'Free browser extension',
  installHeading: 'Put it into practice.',
  installBody: 'Close tabs by site, remove duplicates and sort what stays.',
  desktopBrowsers: 'Desktop browsers',
  byline: 'By {author}, creator of TabTools',
  updated: 'Updated {date}',
  onThisPage: 'On this page',
  allGuides: 'All guides',
  quickAnswer: 'Quick answer',
  relatedGuides: 'Related guides',
  relatedEyebrow: 'Keep going',
  relatedHeading: 'More ways to organise your tabs.',
  home: 'Home',
  breadcrumb: 'Breadcrumb',
  screenshotNote: 'Screenshots show the English interface; labels may differ in your browser’s language.'
};
